#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
cp 0/alpha.metal.orig 0/alpha.metal
cp 0/T.orig 0/T
setFields -dict system/setFieldsDict_alpha &> log.setFieldsDict_alpha
setFields -dict system/setFieldsDict_T &> log.setFieldsDict_T
touch foam.foam

if [[ "$1" == "-parallel" ]]; then
    runApplication decomposePar
    meshType="$(foamDictionary -entry dynamicFvMesh -value constant/dynamicMeshDict)"
    if [[ "$meshType" != staticFvMesh ]]; then
        # In "Decomposed Case" Paraview expect `constant` directories
        find . -maxdepth 1 -type d -regex '\./processor[0-9][0-9]*' -exec ln -s ../constant {} \;
    fi
    runParallel $application
    # Mesh reconstruction is not needed when a dynamic mesh is used
    # Use "Decomposed Case" in Paraview instead
else
    runApplication $application
fi

echo "All is done!"
